### PR TITLE
Added filter by code_name as a kwarg in IronWorker.tasks(...)

### PR DESCRIPTION
**Pull request by revbucket**
I made some minor modifications to the IronWorker.tasks(...) method to allow a kwarg 'code_name', mirroring the query param in the IronWorker.tasks_by_code_name(...) method. It wasn't until I made my changes that I noticed @cessor had built a very similar PR a few years ago. I think his is better/more conclusive and his tests are great, but obviously requires more significant checking to ensure quality (since it's built on an older version of this package).

Would really appreciate seeing the changes made by either @Cessor or I merged into master!

### CODE REVIEW

**Comment by cessor** [comment]
@revbucket I am glad you liked my tests! I believe your code should be merged, as in my old commit, **kwargs were not present yet. I am glad that you liked my tests, maybe you can adopt them to fit your new case? However, I believe merging your changes will be much simpler! All the best from Germany. 

I am wondering why this feature isn't in there yet (i.e. filtering the tasks by their implementation name). It makes me feel like I'm using it wrong. When I used the client a couple of years ago, I ran into this problem after only a couple of minutes.

**Comment by revbucket** [comment]
I'm all about writing test code but in this case, I felt I'd get my changes merged in much more quickly if I kept my changes to a quick 2-line addendum. I'd have no problem building up these tests once I get my current task to a satisfactory state (hell, I'll probably heavily borrow your stubbing method when I test the code I'm currently working on). 

I'll also state that it seems that when you were using the package in 2014, the method `tasks_by_code_name` didn't exist. I'd use that for my purposes, but I want to also take advantage of the 'from_time' and 'to_time' kwargs. 

Best (from NYC)

**Comment by rdallman** [comment]
@revbucket @cessor thanks! yes, it looks like the original patch was a long time ago, apologies for not getting you any feedback on that (and thanks for the tests), our maintainership of these client bindings is... ad hoc :) I did prefer this change since it's based on newer bindings, I think it satisfies both well. Thanks again!

**Comment by cessor** [comment]
Hey, @rdallman 
I thought about my own last comment. Have look at this twitter post:
https://twitter.com/vickyharp/status/736228835046219779

I implemented the feature, and @revbucket implemented it again. To me this was an essential feature (I ran into this problem after a couple of hours playing with the code), but apparently, people using this client could live without it for a long time. 

Is this actually a good practice to refer to tasks by name? Or is this a usability issue with the api? Should the documentation suggest how to use this api differntly?

**Pull request merged**
